Team6083/2025Overlooking

src/main/java/frc/robot/Command/CoralShooterInWithAutoStopcmd.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/Subsystems/CoralShooterSubsystem.java
寫了 CoralShooter 的 Subsystem ，
寫了 CoralShooterInWithAutoStop 這個 Command
用 DistanceSensor 去感測 Coral 是否已經進入了 Coral 洗車機
=> Coral shooter

vendordeps/PathplannerLib-2025.2.1.json, vendordeps/Phoenix5-5.35.1.json, vendordeps/Phoenix6-25.2.1.json, vendordeps/REVLib-2025.0.2.json
=> feat: new vendor download

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java
feat: Auto 建立很多建構式並放上Smartdashboard
=> feat: Auto 建立很多建構式並放上Smartdashboard

.github/workflows/gradle.yml, vendordeps/REV2mDistanceSensor.json
加入 REV2mDistanceSensor 的 Vender 檔
=> feat : add REV2mDistanceSensor

src/main/java/frc/robot/RobotContainer.java
feat: 把 CoralShooterSubsystem 建構式並放上SmartDashboard
=> feat: 把 CoralShooterSubsystem 建構式並放上SmartDashboard

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/subsystems/PowerDistributionSubsystem.java
新增 PowerDistributionSubsystem 
在 Constants 裡新增 PowerDistributionConstant  , Currentchannel , MaxCurrent 
(っ●ω●)っ
=> feat: add "PowerDistributionSubsystem"

vendordeps/PathplannerLib-2025.2.2.json, vendordeps/Studica-2025.0.1.json
add Studica.json update athplannerLib.json
=> feat: Vendor download and update

src/main/java/frc/robot/Constants.java
測試後調了一些參數
把需要注意的參數用 TODO HighLight 標註起來（我不知道有沒有更好的標註方式，所以就這樣了）
=> 0213 testing

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/commands/SwerveControlCmd.java
=> feat speed change

src/main/java/frc/robot/RobotContainer.java
feat: 建立兩個自動的cmd style: 把autchooser 變 autochooser
=> feat: 建立兩個自動的cmd style: 把autchooser 變 autochooser

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/AlgaeIntakeSubsystem.java, src/main/java/frc/robot/subsystems/CoralShooterSubsystem.java, src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
=> Style after 6998 competition

src/main/java/frc/robot/subsystems/CoralShooterSubsystem.java
fixed:distance sensor 在CoralShooterSubsystem 的public void periodic() 裡面加 distanceSensor.setAutomaticMode(true);
=> fixed:distance sensor

.gitignore, build.gradle
把一個很酷會在 build 和 deploy 的時候儲存資料的東西加進來
=> feat: gversion

build.gradle
=> feat: Australia Time Zone

src/main/java/frc/robot/Constants.java
=> value: motor inverted

src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/CoralShooterHoldCmd.java, src/main/java/frc/robot/commands/SwerveControlCmd.java, src/main/java/frc/robot/drivebase/SwerveDrive.java, src/main/java/frc/robot/drivebase/SwerveModule.java, src/main/java/frc/robot/lib/PowerDistribution.java, src/main/java/frc/robot/subsystems/AlgaeIntakeSubsystem.java, src/main/java/frc/robot/subsystems/CoralShooterSubsystem.java
style:SmartDashBoard name,cmd name,Container
=> Container style

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/CoralShooterHoldCmd.java, src/main/java/frc/robot/commands/CoralShooterInWithAutoStopCmd.java, src/main/java/frc/robot/subsystems/CoralShooterSubsystem.java
把 CoralShooter 改成單馬達
把 DistanceSensor 改到前面
=> Coral shooter 改單馬達

src/main/java/frc/robot/PreferencesClass.java, src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
=> fix:AUCanCoderMagOffset

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/AlgaeIntakeSubsystem.java, src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
algaeShooter 可以一鍵到 L2,L3 拿 algae
=> Double motor elevator with algae

build.gradle, src/main/java/frc/robot/subsystems/TagTrackingSubsystem.java
=> other: update version

src/main/java/frc/robot/ConfigChooser.java, src/main/java/frc/robot/commands/SwerveControlCmd.java
fix: update kMaxHeight value and simplify SwerveControlCmd logic
=> fix-swervecontrol-magnification

src/main/java/frc/robot/RobotContainer.java
Use Button 9 to toggle between coral and algae modes for Button 4 and Button 5
=> coral-algae-mode

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/lib/Elastic.java, src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
add Elastic notifications for elevator encoder status and floor change
=> Elastic notifications

src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/drivebase/SwerveDrive.java
refactor: remove unused SmartDashboard properties in SwerveDrive class
=> fix elastic

src/main/java/frc/robot/RobotContainer.java
feat: add triggers for Elastic tab selection in RobotContainer
=> automatically switch tab

src/main/java/frc/robot/RobotContainer.java
=> style: remove unused import
